### PR TITLE
Changing `pypy` skip

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by tdegeus** [comment]
@conda-forge-admin, rerender

**Comment by tdegeus** [comment]
@isuruf This way of skipping `pypy` seems to work. It looks cleaner to me, but I remember that at some point I was advised to use the global skip to avoid issues related to the multi-output (sorry cannot find a reference). So my question: which should be considered correct? Should this still be considered a bug in conda-smithy?

**Comment by isuruf** [comment]
Without a reference I cannot say.

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
