### PR TITLE
Trying without make

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
It doesn't even look like it's trying it. Can you try adding `ninja` to your `host`?

**Comment by xhochy** [comment]
`ninja` should always be in `build`. Otherwise, cross-compilation will not work. 

Can one of you link me to the relevant code in `scikit-build` where it tries to detect `ninja`? Happy to help here as I don't want any obscure Python dependency in the `ninja` package.

**Comment by henryiii** [comment]
It's in both at the moment. 🤣 It's really weird, it seems scikit-build is not trying to detect Ninja, while it [should](https://github.com/scikit-build/scikit-build/blob/e02c9b391d54dedd7cf1a5c4177bc15436ab4a28/skbuild/platform_specifics/unix.py#L10-L23). It should just be running `cmake -GNinja`, and looking to see if that worked. Though I'm not seeing the failure, it seems to be trying make immediately.

**Comment by henryiii** [comment]
If CMAKE_GENERATOR is set, it will use that, and if it's passed on the command line (unlikely), that also can skip the search. Otherwise, it should search Ninja first then Make.

**Comment by henryiii** [comment]
The other place where it can use the ninja import is in https://github.com/scikit-build/scikit-build/blob/e02c9b391d54dedd7cf1a5c4177bc15436ab4a28/skbuild/cmaker.py#L242-L249 - when using build isolation, ninja "moves" every time you rebuild, so it's necessary to update the path. But that's not applicable for conda builds.

**Comment by xhochy** [comment]
Ah, this needs the python module. It would be nice if there was a fallback in scikit-build that uses `shutil.which('ninja')` to detect it without the Python modile.

**Comment by henryiii** [comment]
If it can't find the Python module, it's supposed to try `cmake -GNinja`, and that should, I think, work. I don't see an obvious example of that happening, though. If `CMAKE_GENERATOR` was set to makefiles, that could cause this. But that shouldn't be the case...

And scikit-build is _about_ to drop Python <3.6, which would enable `shutil.which`. :)

**Comment by tdegeus** [comment]
@henryiii What about using `shutil.which` already if the Python version is sufficiently high?

**Comment by henryiii** [comment]
It shouldn't be required, and it doesn't seem to be trying Ninja and failing, like it should be. Can you print the `env` and see if `CMAKE_GENERATOR=make` is set, perhaps?

**Comment by tdegeus** [comment]
@conda-forge-admin, please rerender

**Comment by tdegeus** [comment]
Indeed @henryiii :
```
CMAKE_GENERATOR=Unix Makefiles
```

**Comment by henryiii** [comment]
Yep, scikit-build will only try `make` then because conda-forge is forcing make.

**Comment by henryiii** [comment]
You can set CMAKE_GENERATOR=Ninja, and really this should only be set (if it gets set at all, it should be CMake's default anyway) if `make` is installed!

**Pull request closed without merging**
